server:
  port: 8002

spring:
  application:
    name: cloud-consumer  # eureka上面的application名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: cloud-consumer-8002   # 修改eureka上的配置信息
