server:
  port: 7003

spring:
  application:
    name: cloud-provider  # eureka上面的application名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/,http://localhost:6003/eureka/
  instance:
    instance-id: cloud-provider-7003   # 修改eureka上的配置信息
