server:
  port: 7001

spring:
  application:
    name: cloud-provider  # eureka上面的application名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/,http://localhost:6003/eureka/  # eureka集群
#      defaultZone: http://localhost:6001/eureka/  # eureka地址 eureka单机
  instance:
    instance-id: cloud-provider-7001   # 修改eureka上的配置信息

# eureka 点进服务的基本信息
info:
  app.name: cloud-provider
  company.name: com.liouwb
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
