server:
  port: 7001

spring:
  application:
    name: cloud-provider  # eureka上面的application名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    instance-id: cloud-provider-7001   # 修改eureka上的配置信息
