server:
  port: 7002

spring:
  application:
    name: cloud-provider  # eureka上面的application名称

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/,http://localhost:6003/eureka/
      defaultZone: http://localhost:6003/eureka/
  instance:
    instance-id: cloud-provider-7002   # 修改eureka上的配置信息

info:
  app.name: cloud-provider
  company.name: com.liouwb
  build.artifactId: $project.artifactId$
  build.version: $project.verson$
